FROM registry.redhat.io/ubi9/python-311

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY mcp_server.py ./
COPY drain.py ./
COPY drain3.ini ./

EXPOSE 9000

CMD ["python", "mcp_server.py"]
